### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by overthink** [tommy20061222/test#1]
Hi Tommy.  Thanks for trying our challenge.  Couple issues:

1) I need a simpler way to run this challenge -- installing a whole web server environment is too complicated.

2) Looking at `sample/testFile.txt` I can see the results are not in the correct format.  In your output each result's listings are an array of strings, but they need to he an array of listing objects.  See http://sortable.com/challenge/ for format details.

Thanks, 
Mark (from sortable.com)

**Comment by tommy20061222** [comment]
Hi, Mark
 Thanks for the review. I updated my code to product the result in an array of objects instead of an array of objects... please take a look at file under sample/testFile.txt.....Thank you
 Tommy

**Comment by tommy20061222** [comment]
Hi, Mark
  Actually PHP comes with command line tool. So if you want to see the result without setting any web server environment, you can simply install PHP only.  
   If you are running on Mac, i think PHP is already installed. But if you are running on windows, go to following website : http://windows.php.net/download/ to download the zip file and add bin directory to the windows environment, so that you can type php in the cmd.
    Assume you successfully have the php installed, then simply go the project folder, execute php index.php, then under the output folder you will see the testFile.txt be generated.
    Please let me know if that solve the problem.........
    Thank you!
    Tommy
